### ISSUE TITLE
Как Компилить? 

### ISSUE THREAD

**Issue by Adefful** [kerbalunion/kerbal_space_station#1]
Слава Навальному

**Comment by Adefful** [comment]
или интерпритировать?

**Comment by Adefful** [comment]
на яве всегда разный ответ

**Comment by Adefful** [comment]
у фортрана походу клиническая смерть

**Comment by kerbalunion** [comment]
Ойфак, видно

**Comment by Adefful** [comment]
решил на яп html скомпилировать вроде все хорошо

**Comment by Adefful** [comment]
ide  для слабаков? решил в ворде

**Comment by kerbalunion** [comment]
![image](https://user-images.githubusercontent.com/24387171/34920700-9fe0f010-f987-11e7-82ae-4095e6c8eb2d.png)
У вас просто иконы не те
